spring:
  application:
    name: sonar
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${DATASOURCE_POOL_SIZE:20}
  sql:
    init:
      mode: always
      platform: postgresql